name: Newsmux Presubmit Test

on:
  pull_request:
    branches: [master]

jobs:
  run_all_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.3"
      - run: go test ./...
